/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Magic Link */
        post: operations["request_magic_link_api_v1_auth_magic_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/magic-link/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Magic Link */
        post: operations["verify_magic_link_api_v1_auth_magic_link_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Session */
        post: operations["refresh_session_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Session */
        get: operations["current_session_api_v1_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Out */
        post: operations["sign_out_api_v1_auth_sign_out_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Erase the record. Not reversible, and not a flag.
         *
         *     Washington's My Health My Data Act gives a working deletion right, and the
         *     product promises the deletion is real. The audit trail of the access and of
         *     the deletion survives by design; it holds field names rather than values.
         */
        delete: operations["delete_account_api_v1_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Consents */
        get: operations["read_consents_api_v1_me_consents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Onboarding */
        post: operations["complete_onboarding_api_v1_me_onboarding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profile */
        get: operations["read_profile_api_v1_me_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_v1_me_profile_patch"];
        trace?: never;
    };
    "/api/v1/me/symptoms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entries */
        get: operations["list_entries_api_v1_me_symptoms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/symptoms/burden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Burden
         * @description The 14-day symptom burden score ending on `as_of`, or today.
         *
         *     Computed server-side so the screen, the PDF, and any future export cannot
         *     disagree about the same patient's score.
         */
        get: operations["read_burden_api_v1_me_symptoms_burden_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/symptoms/burden/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Burden Trend */
        get: operations["read_burden_trend_api_v1_me_symptoms_burden_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/symptoms/{entry_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Entry */
        get: operations["read_entry_api_v1_me_symptoms__entry_date__get"];
        /**
         * Upsert Entry
         * @description Write the entry for one day, creating or replacing it.
         *
         *     PUT rather than POST: the day is the identifier, the operation is idempotent,
         *     and an offline client replaying a queued submission must not produce a second
         *     entry for the same date.
         */
        put: operations["upsert_entry_api_v1_me_symptoms__entry_date__put"];
        post?: never;
        /** Delete Entry */
        delete: operations["delete_entry_api_v1_me_symptoms__entry_date__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Liveness only. Deliberately does not touch the database: the load balancer
         *     should not cycle healthy application containers because Postgres is briefly
         *     unreachable.
         */
        get: operations["liveness_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness: checks the dependency the app cannot serve traffic without.
         */
        get: operations["readiness_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessTokenResponse
         * @description The refresh token is intentionally absent: it is set as an httpOnly cookie
         *     and must never be readable by JavaScript.
         */
        AccessTokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
        };
        /**
         * ConsentAcceptance
         * @description The three documents required to hold an account.
         *
         *     Three separate booleans rather than one "I agree": Washington's My Health My
         *     Data Act requires specific consent to the consumer health data disclosure,
         *     and a single checkbox covering everything is exactly what it prohibits.
         *     Research participation is deliberately not here — it is a separate decision,
         *     made later, and never a condition of using the product.
         */
        ConsentAcceptance: {
            /** Consumer Health Data */
            consumer_health_data: boolean;
            /** Privacy Policy */
            privacy_policy: boolean;
            /** Terms Of Service */
            terms_of_service: boolean;
        };
        /** ConsentRecord */
        ConsentRecord: {
            /** Consent Type */
            consent_type: string;
            /** Document Version */
            document_version: string;
            /** Granted */
            granted: boolean;
            /**
             * Granted At
             * Format: date-time
             */
            granted_at: string;
        };
        /**
         * CopingAction
         * @description What the patient did when food stuck.
         *
         *     Recorded because it is the clearest signal of severity a patient can report
         *     reliably, and because the behavioural adaptations are what a
         *     gastroenterologist asks about and patients forget by the appointment.
         * @enum {string}
         */
        CopingAction: "drank_liquid" | "extra_chewing" | "spit_out" | "left_table" | "induced_vomit" | "er_visit";
        /**
         * DysphagiaSeverity
         * @description Graded by what the patient had to do about it, not by a 1-10 feeling.
         *
         *     A self-reported intensity number is not comparable between patients or
         *     against a trial cohort. "Did it stick, and did you need help getting it down"
         *     is observable, and it is the distinction the DSQ itself draws.
         * @enum {string}
         */
        DysphagiaSeverity: "none" | "mild_slow" | "stuck_self_resolved" | "stuck_intervention";
        /**
         * EntryMethod
         * @description Whether the entry was logged on the day it describes.
         *
         *     Research weights same-day entries more heavily than recalled ones, and this
         *     is derived server-side from the patient's own timezone rather than trusted
         *     from the client.
         * @enum {string}
         */
        EntryMethod: "same_day" | "backfill";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MagicLinkRequest */
        MagicLinkRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /**
         * MagicLinkRequestAccepted
         * @description Deliberately uniform response.
         *
         *     Always reports that a link was sent, whether or not the address has an
         *     account, so the endpoint cannot be used to enumerate registered patients —
         *     which for this product would disclose who has an EoE diagnosis.
         */
        MagicLinkRequestAccepted: {
            /**
             * Detail
             * @default If that address can receive mail, a sign-in link is on its way.
             */
            detail: string;
        };
        /** MagicLinkVerify */
        MagicLinkVerify: {
            /** Token */
            token: string;
        };
        /** OnboardingRequest */
        OnboardingRequest: {
            /** Birth Year */
            birth_year: number;
            consents: components["schemas"]["ConsentAcceptance"];
            /** Diagnosis Month */
            diagnosis_month?: string | null;
            /** Display Name */
            display_name?: string | null;
            sex_at_birth?: components["schemas"]["SexAtBirth"] | null;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /**
         * OnboardingResponse
         * @description Carries a fresh access token because the old one predates the patient row.
         *
         *     The access token embeds the patient id, and every patient-scoped route reads
         *     it from there rather than from the request. Returning a new token here saves
         *     the client an immediate refresh round trip to become usable.
         */
        OnboardingResponse: {
            /** Access Token */
            access_token: string;
            /** Consents */
            consents: components["schemas"]["ConsentRecord"][];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            patient: components["schemas"]["PatientProfile"];
            /**
             * Token Type
             * @default Bearer
             */
            token_type: string;
        };
        /** PatientProfile */
        PatientProfile: {
            /** Birth Year */
            birth_year: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Diagnosis Month */
            diagnosis_month: string | null;
            /** Display Name */
            display_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            sex_at_birth: components["schemas"]["SexAtBirth"] | null;
            /** Timezone */
            timezone: string;
        };
        /**
         * PatientProfileUpdate
         * @description Every field optional: this is a PATCH, and an absent field is untouched.
         *
         *     birth_year and sex_at_birth are absent on purpose. They gate eligibility and
         *     describe the research cohort, so changing them is a support action with an
         *     audit trail, not a profile edit.
         */
        PatientProfileUpdate: {
            /** Diagnosis Month */
            diagnosis_month?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** SessionUser */
        SessionUser: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Email Verified */
            email_verified: boolean;
            /** Id */
            id: string;
            /**
             * Onboarding Complete
             * @default false
             */
            onboarding_complete: boolean;
            /** Patient Id */
            patient_id?: string | null;
            /** Role */
            role: string;
        };
        /**
         * SexAtBirth
         * @enum {string}
         */
        SexAtBirth: "female" | "male" | "intersex" | "undisclosed";
        /**
         * SymptomBurdenRead
         * @description A scored window, or an explicit null score with the reason in components.
         *
         *     `score` is null rather than zero when too few days were logged. Dividing three
         *     answered days across a fourteen-day window would render a badly-tracked
         *     fortnight as remission, which is the most damaging thing this endpoint could
         *     get wrong.
         */
        SymptomBurdenRead: {
            /** Components */
            components: {
                [key: string]: unknown;
            };
            /** Days In Window */
            days_in_window: number;
            /** Days Logged */
            days_logged: number;
            /** Days Scorable */
            days_scorable: number;
            /** Instrument Code */
            instrument_code: string;
            /** Instrument Version */
            instrument_version: string;
            /** Max Score */
            max_score: number;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /** Score */
            score: number | null;
        };
        /** SymptomBurdenTrend */
        SymptomBurdenTrend: {
            /** Points */
            points: components["schemas"]["SymptomBurdenRead"][];
        };
        /**
         * SymptomEntryInput
         * @description One day, as the patient answers it.
         *
         *     entry_date is absent deliberately: it comes from the URL, so a body and a
         *     path cannot disagree about which day is being written.
         */
        SymptomEntryInput: {
            /** Ate Solid Food */
            ate_solid_food: boolean;
            /**
             * Ate Unusually Slowly
             * @default false
             */
            ate_unusually_slowly: boolean;
            /**
             * Avoided Foods Today
             * @default false
             */
            avoided_foods_today: boolean;
            /** Coping Actions */
            coping_actions?: components["schemas"]["CopingAction"][];
            /** Dysphagia Occurred */
            dysphagia_occurred?: boolean | null;
            dysphagia_severity?: components["schemas"]["DysphagiaSeverity"] | null;
            /**
             * Food Impaction Er Visit
             * @default false
             */
            food_impaction_er_visit: boolean;
            /**
             * Modified Foods Today
             * @default false
             */
            modified_foods_today: boolean;
            /** Notes */
            notes?: string | null;
            /** Odynophagia */
            odynophagia?: boolean | null;
            /** Odynophagia Severity */
            odynophagia_severity?: number | null;
        };
        /** SymptomEntryList */
        SymptomEntryList: {
            /** Entries */
            entries: components["schemas"]["SymptomEntryRead"][];
            /**
             * Range End
             * Format: date
             */
            range_end: string;
            /**
             * Range Start
             * Format: date
             */
            range_start: string;
        };
        /** SymptomEntryRead */
        SymptomEntryRead: {
            /** Ate Solid Food */
            ate_solid_food: boolean;
            /** Ate Unusually Slowly */
            ate_unusually_slowly: boolean;
            /** Avoided Foods Today */
            avoided_foods_today: boolean;
            /** Coping Actions */
            coping_actions: components["schemas"]["CopingAction"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Daily Score */
            daily_score?: number | null;
            /** Dysphagia Occurred */
            dysphagia_occurred: boolean | null;
            dysphagia_severity: components["schemas"]["DysphagiaSeverity"] | null;
            /**
             * Entry Date
             * Format: date
             */
            entry_date: string;
            entry_method: components["schemas"]["EntryMethod"];
            /** Food Impaction Er Visit */
            food_impaction_er_visit: boolean;
            /** Instrument Code */
            instrument_code: string;
            /** Instrument Version */
            instrument_version: string;
            /** Modified Foods Today */
            modified_foods_today: boolean;
            /** Notes */
            notes: string | null;
            /** Odynophagia */
            odynophagia: boolean | null;
            /** Odynophagia Severity */
            odynophagia_severity: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    request_magic_link_api_v1_auth_magic_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagicLinkRequestAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_magic_link_api_v1_auth_magic_link_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkVerify"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_session_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessTokenResponse"];
                };
            };
        };
    };
    current_session_api_v1_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
        };
    };
    sign_out_api_v1_auth_sign_out_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_account_api_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    read_consents_api_v1_me_consents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentRecord"][];
                };
            };
        };
    };
    complete_onboarding_api_v1_me_onboarding_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_profile_api_v1_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientProfile"];
                };
            };
        };
    };
    update_profile_api_v1_me_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entries_api_v1_me_symptoms_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymptomEntryList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_burden_api_v1_me_symptoms_burden_get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymptomBurdenRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_burden_trend_api_v1_me_symptoms_burden_trend_get: {
        parameters: {
            query?: {
                as_of?: string | null;
                points?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymptomBurdenTrend"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_entry_api_v1_me_symptoms__entry_date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymptomEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_entry_api_v1_me_symptoms__entry_date__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SymptomEntryInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymptomEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entry_api_v1_me_symptoms__entry_date__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
