#!/usr/bin/env bash
# Generate infra/local-prod.env with real values.
#
# Real, not placeholders: with ENVIRONMENT=staging the application compares its
# configured secrets against the development defaults, and a stack running those
# defaults never exercises the comparison it exists to make.
set -euo pipefail
source "$(dirname "$0")/lib.sh"

TARGET="$REPO_ROOT/infra/local-prod.env"

if [[ -f "$TARGET" ]]; then
    log "$TARGET already exists; leaving it alone"
    exit 0
fi

require_cmd openssl

{
    echo "# Generated by scripts/secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "# Local only. Never commit this file."
    echo "JWT_SECRET=$(openssl rand -hex 32)"
    echo "FIELD_ENCRYPTION_KEY=$(openssl rand -base64 32 | tr '+/' '-_' | tr -d '=')"
} > "$TARGET"

chmod 600 "$TARGET"
log "wrote $TARGET"
