"""Initial schema: identity, consent, audit trail, and authentication tokens.

Hand-written rather than autogenerated. Autogenerate cannot express row-level
security policies, role grants, or the append-only constraint on the audit log,
and those are the parts that carry the security properties.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-15

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Tables carrying patient-owned data. Row-level security is applied to each as a
# backstop behind the scoped-repository pattern in the application. The list grows
# as clinical tables land; every new patient-scoped table must be added here.
RLS_TABLES = ("patients", "consents")


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    user_role = postgresql.ENUM(
        "patient", "doctor", "researcher", "admin", name="user_role", create_type=False
    )
    user_status = postgresql.ENUM(
        "active", "suspended", "deleted", name="user_status", create_type=False
    )
    sex_at_birth = postgresql.ENUM(
        "female", "male", "intersex", "undisclosed", name="sex_at_birth", create_type=False
    )
    consent_type = postgresql.ENUM(
        "terms_of_service",
        "privacy_policy",
        "consumer_health_data",
        "research_participation",
        name="consent_type",
        create_type=False,
    )
    research_scope = postgresql.ENUM(
        "symptoms",
        "diet",
        "medications",
        "endoscopy",
        "demographics",
        name="research_scope",
        create_type=False,
    )
    audit_outcome = postgresql.ENUM(
        "success", "denied", "error", name="audit_outcome", create_type=False
    )

    for enum in (
        user_role,
        user_status,
        sex_at_birth,
        consent_type,
        research_scope,
        audit_outcome,
    ):
        enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("role", user_role, nullable=False, server_default="patient"),
        sa.Column("status", user_status, nullable=False, server_default="active"),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("mfa_secret_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    op.create_table(
        "patients",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("birth_year", sa.SmallInteger(), nullable=True),
        sa.Column("sex_at_birth", sex_at_birth, nullable=True),
        sa.Column("diagnosis_month", sa.Date(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False, server_default="UTC"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="pk_patients"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_patients_user_id_users", ondelete="CASCADE"
        ),
        sa.UniqueConstraint("user_id", name="uq_patients_user_id"),
        sa.CheckConstraint(
            "birth_year IS NULL OR (birth_year BETWEEN 1900 AND 2100)",
            name="ck_patients_birth_year_plausible",
        ),
    )

    op.create_table(
        "consents",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("patient_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("consent_type", consent_type, nullable=False),
        sa.Column("document_version", sa.String(length=64), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column(
            "granted_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_consents"),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name="fk_consents_patient_id_patients",
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_consents_current", "consents", ["patient_id", "consent_type", "granted_at"])

    op.create_table(
        "research_consent_scopes",
        sa.Column("consent_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("scope", research_scope, nullable=False),
        sa.PrimaryKeyConstraint("consent_id", "scope", name="pk_research_consent_scopes"),
        sa.ForeignKeyConstraint(
            ["consent_id"],
            ["consents.id"],
            name="fk_research_consent_scopes_consent_id_consents",
            ondelete="CASCADE",
        ),
    )

    op.create_table(
        "magic_link_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_ip", postgresql.INET(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_magic_link_tokens"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_magic_link_tokens_user_id_users",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint("token_hash", name="uq_magic_link_tokens_token_hash"),
    )
    op.create_index(
        "ix_magic_link_tokens_user_id_expires_at",
        "magic_link_tokens",
        ["user_id", "expires_at"],
    )

    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("family_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_refresh_tokens"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_refresh_tokens_user_id_users", ondelete="CASCADE"
        ),
        sa.UniqueConstraint("token_hash", name="uq_refresh_tokens_token_hash"),
    )
    op.create_index(
        "ix_refresh_tokens_user_id_expires_at", "refresh_tokens", ["user_id", "expires_at"]
    )
    op.create_index("ix_refresh_tokens_family_id", "refresh_tokens", ["family_id"])

    # No foreign keys: the audit trail must survive deletion of the user and
    # patient it refers to, including the record of the deletion itself.
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("actor_role", sa.String(length=32), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("patient_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("outcome", audit_outcome, nullable=False),
        sa.Column("metadata", postgresql.JSONB(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_audit_log"),
    )
    op.create_index(
        "ix_audit_log_patient_id_occurred_at", "audit_log", ["patient_id", "occurred_at"]
    )
    op.create_index("ix_audit_log_action_occurred_at", "audit_log", ["action", "occurred_at"])

    _apply_row_level_security()
    _apply_runtime_grants()


def _apply_row_level_security() -> None:
    """Enable RLS as a backstop behind application-level scoping.

    NULLIF guards the unset case: an unscoped session yields NULL, which matches
    no row, so a forgotten filter returns nothing instead of another patient's data.

    Statements are issued one at a time because asyncpg prepares each one and
    rejects multi-command strings.
    """
    scope = "NULLIF(current_setting('app.current_patient_id', true), '')::uuid"

    # patients is keyed on its own id; every other patient-owned table joins via patient_id.
    op.execute("ALTER TABLE patients ENABLE ROW LEVEL SECURITY")
    op.execute(f"CREATE POLICY patient_isolation ON patients USING (id = {scope})")

    for table in ("consents",):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"CREATE POLICY patient_isolation ON {table} USING (patient_id = {scope})")


def _apply_runtime_grants() -> None:
    """Grant the application role only what it needs.

    The role owns no tables, because owners bypass RLS by default and the policies
    above would then be inert. The audit log is INSERT-only so a compromised
    application cannot erase its own trail.
    """
    # A single DO block is one command, so asyncpg accepts it.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_runtime') THEN
                GRANT USAGE ON SCHEMA public TO app_runtime;
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON ALL TABLES IN SCHEMA public TO app_runtime;
                GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_runtime;

                REVOKE UPDATE, DELETE ON audit_log FROM app_runtime;
            END IF;
        END
        $$
        """
    )


def downgrade() -> None:
    op.drop_table("audit_log")
    op.drop_table("refresh_tokens")
    op.drop_table("magic_link_tokens")
    op.drop_table("research_consent_scopes")
    op.drop_table("consents")
    op.drop_table("patients")
    op.drop_table("users")

    for enum_name in (
        "audit_outcome",
        "research_scope",
        "consent_type",
        "sex_at_birth",
        "user_status",
        "user_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
